--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageScope;
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorage;
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream;
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException;
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageSecurityOptions;
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageSecurityState;
with NetFrameworkBase.System.IO.IsolatedStorage.INormalizeForIsolatedStorage;
with NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile;
with NetFrameworkBase.System.IO.FileMode;
with NetFrameworkBase.System.IO.FileAccess;
with NetFrameworkBase.System.IO.FileShare;
with NetFrameworkBase.System.Exception_x;
--------------------------------------------------------------------------------
package NetFramework.System.IO.IsolatedStorage is
   
      subtype IsolatedStorageScope is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageScope.Kind;
      
      subtype IsolatedStorage is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorage.Kind_Ptr;
      subtype IsolatedStorage_Array is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorage.Kind_Array;
      
      subtype IsolatedStorageFileStream is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr;
      subtype IsolatedStorageFileStream_Array is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Array;
      
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            isf : NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile.Kind_Ptr
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            access_x : NetFrameworkBase.System.IO.FileAccess.Kind
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            access_x : NetFrameworkBase.System.IO.FileAccess.Kind;
            isf : NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile.Kind_Ptr
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            access_x : NetFrameworkBase.System.IO.FileAccess.Kind;
            share : NetFrameworkBase.System.IO.FileShare.Kind
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            access_x : NetFrameworkBase.System.IO.FileAccess.Kind;
            share : NetFrameworkBase.System.IO.FileShare.Kind;
            isf : NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile.Kind_Ptr
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            access_x : NetFrameworkBase.System.IO.FileAccess.Kind;
            share : NetFrameworkBase.System.IO.FileShare.Kind;
            bufferSize : NetFrameworkBase.Int32
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
         function Constructor
         (
            path : NetFrameworkBase.BSTR;
            mode : NetFrameworkBase.System.IO.FileMode.Kind;
            access_x : NetFrameworkBase.System.IO.FileAccess.Kind;
            share : NetFrameworkBase.System.IO.FileShare.Kind;
            bufferSize : NetFrameworkBase.Int32;
            isf : NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile.Kind_Ptr
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFileStream.Constructor; 
         
      subtype IsolatedStorageException is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Kind_Ptr;
      subtype IsolatedStorageException_Array is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Kind_Array;
      
         function Constructor return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Constructor;
         
         function Constructor
         (
            message : NetFrameworkBase.BSTR
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Constructor; 
         
         function Constructor
         (
            message : NetFrameworkBase.BSTR;
            inner : NetFrameworkBase.System.Exception_x.Kind_Ptr
         )
         return NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Kind_Ptr renames NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageException.Constructor; 
         
      subtype IsolatedStorageSecurityOptions is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageSecurityOptions.Kind;
      
      subtype IsolatedStorageSecurityState is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageSecurityState.Kind_Ptr;
      subtype IsolatedStorageSecurityState_Array is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageSecurityState.Kind_Array;
      
      subtype INormalizeForIsolatedStorage is NetFrameworkBase.System.IO.IsolatedStorage.INormalizeForIsolatedStorage.Kind_Ptr;
      subtype INormalizeForIsolatedStorage_Array is NetFrameworkBase.System.IO.IsolatedStorage.INormalizeForIsolatedStorage.Kind_Array;
      
      subtype IsolatedStorageFile is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile.Kind_Ptr;
      subtype IsolatedStorageFile_Array is NetFrameworkBase.System.IO.IsolatedStorage.IsolatedStorageFile.Kind_Array;
      
   
end;
