--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash;
with NetFrameworkBase.System.Configuration.Assemblies.AssemblyHashAlgorithm;
with NetFrameworkBase.System.Configuration.Assemblies.AssemblyVersionCompatibility;
--------------------------------------------------------------------------------
package NetFramework.System.Configuration.Assemblies is
   
      --------------------------------------------------------------------------
      subtype AssemblyHash is NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash.Kind_Ptr;
      subtype AssemblyHash_Array is NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash.Kind_Array;
      
         function Constructor
         (
            value : NetFrameworkBase.Byte_Array
         )
         return NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash.Kind_Ptr renames NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash.Constructor; 
         
         function Constructor
         (
            algorithm : NetFrameworkBase.System.Configuration.Assemblies.AssemblyHashAlgorithm.Kind;
            value : NetFrameworkBase.Byte_Array
         )
         return NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash.Kind_Ptr renames NetFrameworkBase.System.Configuration.Assemblies.AssemblyHash.Constructor; 
         
      --------------------------------------------------------------------------
      subtype AssemblyHashAlgorithm is NetFrameworkBase.System.Configuration.Assemblies.AssemblyHashAlgorithm.Kind;
      
      --------------------------------------------------------------------------
      subtype AssemblyVersionCompatibility is NetFrameworkBase.System.Configuration.Assemblies.AssemblyVersionCompatibility.Kind;
      
   
end;
