--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.CodeDom.CodeTypeMember;
limited with NetFrameworkBase.System.Reflection.TypeAttributes;
limited with NetFrameworkBase.System.EventHandler;
limited with NetFrameworkBase.System.CodeDom.CodeTypeReferenceCollection;
limited with NetFrameworkBase.System.CodeDom.CodeTypeMemberCollection;
limited with NetFrameworkBase.System.CodeDom.CodeTypeParameterCollection;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.CodeDom.CodeTypeDeclaration is
   
   type Kind is new NetFrameworkBase.System.CodeDom.CodeTypeMember.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function BaseTypes
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.System.CodeDom.CodeTypeReferenceCollection.Kind_Ptr;
      
      function Members
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.System.CodeDom.CodeTypeMemberCollection.Kind_Ptr;
      
      function TypeAttributes
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.System.Reflection.TypeAttributes.Kind;
      
      procedure TypeAttributes
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.System.Reflection.TypeAttributes.Kind
      );
      
      function IsClass
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.Boolean;
      
      procedure IsClass
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.Boolean
      );
      
      function IsStruct
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.Boolean;
      
      procedure IsStruct
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.Boolean
      );
      
      function IsEnum
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.Boolean;
      
      procedure IsEnum
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.Boolean
      );
      
      function IsInterface
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.Boolean;
      
      procedure IsInterface
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.Boolean
      );
      
      function IsPartial
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.Boolean;
      
      procedure IsPartial
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.Boolean
      );
      
      function TypeParameters
      (
         this : in out CodeTypeDeclaration.Kind
      )
      return NetFrameworkBase.System.CodeDom.CodeTypeParameterCollection.Kind_Ptr;
      
      procedure add_PopulateBaseTypes
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.System.EventHandler.Kind_Ptr
      );
      
      procedure remove_PopulateBaseTypes
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.System.EventHandler.Kind_Ptr
      );
      
      procedure add_PopulateMembers
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.System.EventHandler.Kind_Ptr
      );
      
      procedure remove_PopulateMembers
      (
         this : in out CodeTypeDeclaration.Kind;
         value : NetFrameworkBase.System.EventHandler.Kind_Ptr
      );
      
      function Constructor return NetFrameworkBase.System.CodeDom.CodeTypeDeclaration.Kind_Ptr;
      
      function Constructor
      (
         name : NetFrameworkBase.BSTR
      )
      return NetFrameworkBase.System.CodeDom.CodeTypeDeclaration.Kind_Ptr;
      
end;
