--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.Security.Cryptography.Aes;
limited with NetFrameworkBase.System.Security.Cryptography.CipherMode;
limited with NetFrameworkBase.System.Security.Cryptography.PaddingMode;
limited with NetFrameworkBase.System.Security.Cryptography.ICryptoTransform;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.Security.Cryptography.AesManaged is
   
   type Kind is new NetFrameworkBase.System.Security.Cryptography.Aes.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function FeedbackSize
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.Int32;
      
      procedure FeedbackSize
      (
         this : in out AesManaged.Kind;
         value : NetFrameworkBase.Int32
      );
      
      function IV
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.Byte_Array;
      
      procedure IV
      (
         this : in out AesManaged.Kind;
         value : NetFrameworkBase.Byte_Array
      );
      
      function Key
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.Byte_Array;
      
      procedure Key
      (
         this : in out AesManaged.Kind;
         value : NetFrameworkBase.Byte_Array
      );
      
      function KeySize
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.Int32;
      
      procedure KeySize
      (
         this : in out AesManaged.Kind;
         value : NetFrameworkBase.Int32
      );
      
      function Mode
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.System.Security.Cryptography.CipherMode.Kind;
      
      procedure Mode
      (
         this : in out AesManaged.Kind;
         value : NetFrameworkBase.System.Security.Cryptography.CipherMode.Kind
      );
      
      function Padding
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.System.Security.Cryptography.PaddingMode.Kind;
      
      procedure Padding
      (
         this : in out AesManaged.Kind;
         value : NetFrameworkBase.System.Security.Cryptography.PaddingMode.Kind
      );
      
      function CreateDecryptor
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.System.Security.Cryptography.ICryptoTransform.Kind_Ptr;
      
      function CreateDecryptor
      (
         this : in out AesManaged.Kind;
         key : NetFrameworkBase.Byte_Array; 
         iv : NetFrameworkBase.Byte_Array
      )
      return NetFrameworkBase.System.Security.Cryptography.ICryptoTransform.Kind_Ptr;
      
      function CreateEncryptor
      (
         this : in out AesManaged.Kind
      )
      return NetFrameworkBase.System.Security.Cryptography.ICryptoTransform.Kind_Ptr;
      
      function CreateEncryptor
      (
         this : in out AesManaged.Kind;
         key : NetFrameworkBase.Byte_Array; 
         iv : NetFrameworkBase.Byte_Array
      )
      return NetFrameworkBase.System.Security.Cryptography.ICryptoTransform.Kind_Ptr;
      
      procedure GenerateIV
      (
         this : in out AesManaged.Kind
      );
      
      procedure GenerateKey
      (
         this : in out AesManaged.Kind
      );
      
      function Constructor return NetFrameworkBase.System.Security.Cryptography.AesManaged.Kind_Ptr;
      
end;
