--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.IO.Stream;
limited with NetFrameworkBase.System.IO.SeekOrigin;
limited with NetFrameworkBase.System.AsyncCallback;
with NetFrameworkBase.System.Object;
limited with NetFrameworkBase.System.IAsyncResult;
limited with NetFrameworkBase.System.IO.Compression.CompressionMode;
limited with NetFrameworkBase.System.IO.Compression.CompressionLevel;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.IO.Compression.DeflateStream is
   
   type Kind is new NetFrameworkBase.System.IO.Stream.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function CanRead
      (
         this : in out DeflateStream.Kind
      )
      return NetFrameworkBase.Boolean;
      
      function CanWrite
      (
         this : in out DeflateStream.Kind
      )
      return NetFrameworkBase.Boolean;
      
      function CanSeek
      (
         this : in out DeflateStream.Kind
      )
      return NetFrameworkBase.Boolean;
      
      function Length
      (
         this : in out DeflateStream.Kind
      )
      return NetFrameworkBase.Int64;
      
      function Position
      (
         this : in out DeflateStream.Kind
      )
      return NetFrameworkBase.Int64;
      
      procedure Position
      (
         this : in out DeflateStream.Kind;
         value : NetFrameworkBase.Int64
      );
      
      procedure Flush
      (
         this : in out DeflateStream.Kind
      );
      
      function Seek
      (
         this : in out DeflateStream.Kind;
         offset : NetFrameworkBase.Int64; 
         origin : NetFrameworkBase.System.IO.SeekOrigin.Kind
      )
      return NetFrameworkBase.Int64;
      
      procedure SetLength
      (
         this : in out DeflateStream.Kind;
         value : NetFrameworkBase.Int64
      );
      
      function Read
      (
         this : in out DeflateStream.Kind;
         array_x : in out NetFrameworkBase.Byte_Array; 
         offset : NetFrameworkBase.Int32; 
         count : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Int32;
      
      function BeginRead
      (
         this : in out DeflateStream.Kind;
         array_x : NetFrameworkBase.Byte_Array; 
         offset : NetFrameworkBase.Int32; 
         count : NetFrameworkBase.Int32; 
         asyncCallback : NetFrameworkBase.System.AsyncCallback.Kind_Ptr; 
         asyncState : NetFrameworkBase.System.Object.Kind_Ptr
      )
      return NetFrameworkBase.System.IAsyncResult.Kind_Ptr;
      
      function EndRead
      (
         this : in out DeflateStream.Kind;
         asyncResult : NetFrameworkBase.System.IAsyncResult.Kind_Ptr
      )
      return NetFrameworkBase.Int32;
      
      procedure Write
      (
         this : in out DeflateStream.Kind;
         array_x : NetFrameworkBase.Byte_Array; 
         offset : NetFrameworkBase.Int32; 
         count : NetFrameworkBase.Int32
      );
      
      function BeginWrite
      (
         this : in out DeflateStream.Kind;
         array_x : NetFrameworkBase.Byte_Array; 
         offset : NetFrameworkBase.Int32; 
         count : NetFrameworkBase.Int32; 
         asyncCallback : NetFrameworkBase.System.AsyncCallback.Kind_Ptr; 
         asyncState : NetFrameworkBase.System.Object.Kind_Ptr
      )
      return NetFrameworkBase.System.IAsyncResult.Kind_Ptr;
      
      procedure EndWrite
      (
         this : in out DeflateStream.Kind;
         asyncResult : NetFrameworkBase.System.IAsyncResult.Kind_Ptr
      );
      
      function BaseStream
      (
         this : in out DeflateStream.Kind
      )
      return NetFrameworkBase.System.IO.Stream.Kind_Ptr;
      
      function Constructor
      (
         stream : NetFrameworkBase.System.IO.Stream.Kind_Ptr;
         mode : NetFrameworkBase.System.IO.Compression.CompressionMode.Kind
      )
      return NetFrameworkBase.System.IO.Compression.DeflateStream.Kind_Ptr;
      
      function Constructor
      (
         stream : NetFrameworkBase.System.IO.Stream.Kind_Ptr;
         mode : NetFrameworkBase.System.IO.Compression.CompressionMode.Kind;
         leaveOpen : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.IO.Compression.DeflateStream.Kind_Ptr;
      
      function Constructor
      (
         stream : NetFrameworkBase.System.IO.Stream.Kind_Ptr;
         compressionLevel : NetFrameworkBase.System.IO.Compression.CompressionLevel.Kind
      )
      return NetFrameworkBase.System.IO.Compression.DeflateStream.Kind_Ptr;
      
      function Constructor
      (
         stream : NetFrameworkBase.System.IO.Stream.Kind_Ptr;
         compressionLevel : NetFrameworkBase.System.IO.Compression.CompressionLevel.Kind;
         leaveOpen : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.IO.Compression.DeflateStream.Kind_Ptr;
      
end;
