--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.Attribute;
limited with NetFrameworkBase.System.Type_x;
with NetFrameworkBase.System.Object;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.ComponentModel.Design.Serialization.DesignerSerializerAttribute is
   
   type Kind is new NetFrameworkBase.System.Attribute.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function SerializerTypeName
      (
         this : in out DesignerSerializerAttribute.Kind
      )
      return NetFrameworkBase.BSTR;
      
      function SerializerBaseTypeName
      (
         this : in out DesignerSerializerAttribute.Kind
      )
      return NetFrameworkBase.BSTR;
      
      function TypeId
      (
         this : in out DesignerSerializerAttribute.Kind
      )
      return NetFrameworkBase.System.Object.Kind_Ptr;
      
      function Constructor
      (
         serializerType : NetFrameworkBase.System.Type_x.Kind_Ptr;
         baseSerializerType : NetFrameworkBase.System.Type_x.Kind_Ptr
      )
      return NetFrameworkBase.System.ComponentModel.Design.Serialization.DesignerSerializerAttribute.Kind_Ptr;
      
      function Constructor
      (
         serializerTypeName : NetFrameworkBase.BSTR;
         baseSerializerType : NetFrameworkBase.System.Type_x.Kind_Ptr
      )
      return NetFrameworkBase.System.ComponentModel.Design.Serialization.DesignerSerializerAttribute.Kind_Ptr;
      
      function Constructor
      (
         serializerTypeName : NetFrameworkBase.BSTR;
         baseSerializerTypeName : NetFrameworkBase.BSTR
      )
      return NetFrameworkBase.System.ComponentModel.Design.Serialization.DesignerSerializerAttribute.Kind_Ptr;
      
end;
