--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.ValueType;
limited with NetFrameworkBase.System.TimeSpan;
with NetFrameworkBase.System.Object;
limited with NetFrameworkBase.System.IFormatProvider;
limited with NetFrameworkBase.System.Globalization.DateTimeStyles;
limited with NetFrameworkBase.System.Globalization.Calendar;
limited with NetFrameworkBase.System.DayOfWeek;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.DateTimeOffset is
   
   type Kind is new NetFrameworkBase.System.ValueType.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function Now
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function UtcNow
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function DateTime
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Date;
      
      function UtcDateTime
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Date;
      
      function LocalDateTime
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Date;
      
      function ToOffset
      (
         this : in out DateTimeOffset.Kind;
         offset : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Date
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Date;
      
      function Day
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function DayOfWeek
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.System.DayOfWeek.Kind;
      
      function DayOfYear
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Hour
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Millisecond
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Minute
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Month
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Offset
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.System.TimeSpan.Kind_Ptr;
      
      function Second
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Ticks
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int64;
      
      function UtcTicks
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int64;
      
      function TimeOfDay
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.System.TimeSpan.Kind_Ptr;
      
      function Year
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Add
      (
         this : in out DateTimeOffset.Kind;
         timeSpan : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddDays
      (
         this : in out DateTimeOffset.Kind;
         days : NetFrameworkBase.Double
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddHours
      (
         this : in out DateTimeOffset.Kind;
         hours : NetFrameworkBase.Double
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddMilliseconds
      (
         this : in out DateTimeOffset.Kind;
         milliseconds : NetFrameworkBase.Double
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddMinutes
      (
         this : in out DateTimeOffset.Kind;
         minutes : NetFrameworkBase.Double
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddMonths
      (
         this : in out DateTimeOffset.Kind;
         months : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddSeconds
      (
         this : in out DateTimeOffset.Kind;
         seconds : NetFrameworkBase.Double
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddTicks
      (
         this : in out DateTimeOffset.Kind;
         ticks : NetFrameworkBase.Int64
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function AddYears
      (
         this : in out DateTimeOffset.Kind;
         years : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Compare
      (
         first : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         second : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Int32;
      
      function CompareTo
      (
         this : in out DateTimeOffset.Kind;
         other : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Int32;
      
      function Equals
      (
         this : in out DateTimeOffset.Kind;
         obj : NetFrameworkBase.System.Object.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function Equals
      (
         this : in out DateTimeOffset.Kind;
         other : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function EqualsExact
      (
         this : in out DateTimeOffset.Kind;
         other : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function Equals
      (
         first : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         second : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function FromFileTime
      (
         fileTime : NetFrameworkBase.Int64
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function FromUnixTimeSeconds
      (
         seconds : NetFrameworkBase.Int64
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function FromUnixTimeMilliseconds
      (
         milliseconds : NetFrameworkBase.Int64
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function GetHashCode
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Parse
      (
         input : NetFrameworkBase.BSTR
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Parse
      (
         input : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function ParseExact
      (
         input : NetFrameworkBase.BSTR;
         format : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Subtract
      (
         this : in out DateTimeOffset.Kind;
         value : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.System.TimeSpan.Kind_Ptr;
      
      function Subtract
      (
         this : in out DateTimeOffset.Kind;
         value : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function ToFileTime
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int64;
      
      function ToUnixTimeSeconds
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int64;
      
      function ToUnixTimeMilliseconds
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.Int64;
      
      function ToLocalTime
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function ToString
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.BSTR;
      
      function ToString
      (
         this : in out DateTimeOffset.Kind;
         format : NetFrameworkBase.BSTR
      )
      return NetFrameworkBase.BSTR;
      
      function ToString
      (
         this : in out DateTimeOffset.Kind;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr
      )
      return NetFrameworkBase.BSTR;
      
      function ToString
      (
         this : in out DateTimeOffset.Kind;
         format : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr
      )
      return NetFrameworkBase.BSTR;
      
      function ToUniversalTime
      (
         this : in out DateTimeOffset.Kind
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function TryParse
      (
         input : NetFrameworkBase.BSTR;
         result : out NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function op_Implicit
      (
         dateTime : NetFrameworkBase.Date
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function op_Addition
      (
         dateTimeOffset : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         timeSpan : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function op_Subtraction
      (
         dateTimeOffset : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         timeSpan : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function op_Subtraction
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.System.TimeSpan.Kind_Ptr;
      
      function op_Equality
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function op_Inequality
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function op_LessThan
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function op_LessThanOrEqual
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function op_GreaterThan
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function op_GreaterThanOrEqual
      (
         left : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
         right : NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function Parse
      (
         input : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr;
         styles : NetFrameworkBase.System.Globalization.DateTimeStyles.Kind
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function ParseExact
      (
         input : NetFrameworkBase.BSTR;
         format : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr;
         styles : NetFrameworkBase.System.Globalization.DateTimeStyles.Kind
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function ParseExact
      (
         input : NetFrameworkBase.BSTR;
         formats : NetFrameworkBase.BSTR_Array;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr;
         styles : NetFrameworkBase.System.Globalization.DateTimeStyles.Kind
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function TryParse
      (
         input : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr;
         styles : NetFrameworkBase.System.Globalization.DateTimeStyles.Kind;
         result : out NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function TryParseExact
      (
         input : NetFrameworkBase.BSTR;
         formats : NetFrameworkBase.BSTR_Array;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr;
         styles : NetFrameworkBase.System.Globalization.DateTimeStyles.Kind;
         result : out NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function TryParseExact
      (
         input : NetFrameworkBase.BSTR;
         format : NetFrameworkBase.BSTR;
         formatProvider : NetFrameworkBase.System.IFormatProvider.Kind_Ptr;
         styles : NetFrameworkBase.System.Globalization.DateTimeStyles.Kind;
         result : out NetFrameworkBase.System.DateTimeOffset.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function Constructor
      (
         ticks : NetFrameworkBase.Int64;
         offset : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Constructor
      (
         dateTime : NetFrameworkBase.Date
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Constructor
      (
         dateTime : NetFrameworkBase.Date;
         offset : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Constructor
      (
         year : NetFrameworkBase.Int32;
         month : NetFrameworkBase.Int32;
         day : NetFrameworkBase.Int32;
         hour : NetFrameworkBase.Int32;
         minute : NetFrameworkBase.Int32;
         second : NetFrameworkBase.Int32;
         offset : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Constructor
      (
         year : NetFrameworkBase.Int32;
         month : NetFrameworkBase.Int32;
         day : NetFrameworkBase.Int32;
         hour : NetFrameworkBase.Int32;
         minute : NetFrameworkBase.Int32;
         second : NetFrameworkBase.Int32;
         millisecond : NetFrameworkBase.Int32;
         offset : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
      function Constructor
      (
         year : NetFrameworkBase.Int32;
         month : NetFrameworkBase.Int32;
         day : NetFrameworkBase.Int32;
         hour : NetFrameworkBase.Int32;
         minute : NetFrameworkBase.Int32;
         second : NetFrameworkBase.Int32;
         millisecond : NetFrameworkBase.Int32;
         calendar : NetFrameworkBase.System.Globalization.Calendar.Kind_Ptr;
         offset : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.System.DateTimeOffset.Kind_Ptr;
      
end;
