--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.Object;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.Security.Cryptography.CryptoAPITransform is
   
   type Kind is new NetFrameworkBase.System.Object.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      procedure Dispose
      (
         this : in out CryptoAPITransform.Kind
      );
      
      procedure Clear
      (
         this : in out CryptoAPITransform.Kind
      );
      
      function KeyHandle
      (
         this : in out CryptoAPITransform.Kind
      )
      return NetFrameworkBase.IntPtr;
      
      function InputBlockSize
      (
         this : in out CryptoAPITransform.Kind
      )
      return NetFrameworkBase.Int32;
      
      function OutputBlockSize
      (
         this : in out CryptoAPITransform.Kind
      )
      return NetFrameworkBase.Int32;
      
      function CanTransformMultipleBlocks
      (
         this : in out CryptoAPITransform.Kind
      )
      return NetFrameworkBase.Boolean;
      
      function CanReuseTransform
      (
         this : in out CryptoAPITransform.Kind
      )
      return NetFrameworkBase.Boolean;
      
      procedure Reset
      (
         this : in out CryptoAPITransform.Kind
      );
      
      function TransformBlock
      (
         this : in out CryptoAPITransform.Kind;
         inputBuffer : NetFrameworkBase.Byte_Array; 
         inputOffset : NetFrameworkBase.Int32; 
         inputCount : NetFrameworkBase.Int32; 
         outputBuffer : NetFrameworkBase.Byte_Array; 
         outputOffset : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Int32;
      
      function TransformFinalBlock
      (
         this : in out CryptoAPITransform.Kind;
         inputBuffer : NetFrameworkBase.Byte_Array; 
         inputOffset : NetFrameworkBase.Int32; 
         inputCount : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Byte_Array;
      
end;
