--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.CodeDom.Compiler.CodeDomProvider;
limited with NetFrameworkBase.System.Type_x;
limited with NetFrameworkBase.System.CodeDom.CodeTypeMember;
limited with NetFrameworkBase.System.IO.TextWriter;
limited with NetFrameworkBase.System.CodeDom.Compiler.CodeGeneratorOptions;
limited with NetFrameworkBase.System.CodeDom.Compiler.LanguageOptions;
limited with NetFrameworkBase.System.CodeDom.Compiler.ICodeGenerator;
limited with NetFrameworkBase.System.CodeDom.Compiler.ICodeCompiler;
limited with NetFrameworkBase.System.ComponentModel.TypeConverter;
--------------------------------------------------------------------------------
package NetFrameworkBase.Microsoft.VisualBasic.VBCodeProvider is
   
   type Kind is new NetFrameworkBase.System.CodeDom.Compiler.CodeDomProvider.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function FileExtension
      (
         this : in out VBCodeProvider.Kind
      )
      return NetFrameworkBase.BSTR;
      
      function LanguageOptions
      (
         this : in out VBCodeProvider.Kind
      )
      return NetFrameworkBase.System.CodeDom.Compiler.LanguageOptions.Kind;
      
      function CreateGenerator
      (
         this : in out VBCodeProvider.Kind
      )
      return NetFrameworkBase.System.CodeDom.Compiler.ICodeGenerator.Kind_Ptr;
      
      function CreateCompiler
      (
         this : in out VBCodeProvider.Kind
      )
      return NetFrameworkBase.System.CodeDom.Compiler.ICodeCompiler.Kind_Ptr;
      
      function GetConverter
      (
         this : in out VBCodeProvider.Kind;
         type_x : NetFrameworkBase.System.Type_x.Kind_Ptr
      )
      return NetFrameworkBase.System.ComponentModel.TypeConverter.Kind_Ptr;
      
      procedure GenerateCodeFromMember
      (
         this : in out VBCodeProvider.Kind;
         member : NetFrameworkBase.System.CodeDom.CodeTypeMember.Kind_Ptr; 
         writer : NetFrameworkBase.System.IO.TextWriter.Kind_Ptr; 
         options : NetFrameworkBase.System.CodeDom.Compiler.CodeGeneratorOptions.Kind_Ptr
      );
      
      function Constructor return NetFrameworkBase.Microsoft.VisualBasic.VBCodeProvider.Kind_Ptr;
      
end;
