--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.Object;
limited with NetFrameworkBase.System.Threading.WaitHandle;
limited with NetFrameworkBase.System.Threading.WaitOrTimerCallback;
limited with NetFrameworkBase.System.TimeSpan;
limited with NetFrameworkBase.System.Threading.WaitCallback;
limited with NetFrameworkBase.System.Threading.NativeOverlapped;
limited with NetFrameworkBase.System.Runtime.InteropServices.SafeHandle;
limited with NetFrameworkBase.System.Threading.RegisteredWaitHandle;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.Threading.ThreadPool is
   
   type Kind is new NetFrameworkBase.System.Object.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function SetMaxThreads
      (
         workerThreads : NetFrameworkBase.Int32; 
         completionPortThreads : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Boolean;
      
      procedure GetMaxThreads
      (
         workerThreads : out NetFrameworkBase.Int32; 
         completionPortThreads : out NetFrameworkBase.Int32
      )
      ;
      
      function SetMinThreads
      (
         workerThreads : NetFrameworkBase.Int32; 
         completionPortThreads : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Boolean;
      
      procedure GetMinThreads
      (
         workerThreads : out NetFrameworkBase.Int32; 
         completionPortThreads : out NetFrameworkBase.Int32
      )
      ;
      
      procedure GetAvailableThreads
      (
         workerThreads : out NetFrameworkBase.Int32; 
         completionPortThreads : out NetFrameworkBase.Int32
      )
      ;
      
      function RegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         millisecondsTimeOutInterval : NetFrameworkBase.UInt32; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function UnsafeRegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         millisecondsTimeOutInterval : NetFrameworkBase.UInt32; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function RegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         millisecondsTimeOutInterval : NetFrameworkBase.Int32; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function UnsafeRegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         millisecondsTimeOutInterval : NetFrameworkBase.Int32; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function RegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         millisecondsTimeOutInterval : NetFrameworkBase.Int64; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function UnsafeRegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         millisecondsTimeOutInterval : NetFrameworkBase.Int64; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function RegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         timeout : NetFrameworkBase.System.TimeSpan.Kind_Ptr; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function UnsafeRegisterWaitForSingleObject
      (
         waitObject : NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr; 
         callBack : NetFrameworkBase.System.Threading.WaitOrTimerCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr; 
         timeout : NetFrameworkBase.System.TimeSpan.Kind_Ptr; 
         executeOnlyOnce : NetFrameworkBase.Boolean
      )
      return NetFrameworkBase.System.Threading.RegisteredWaitHandle.Kind_Ptr;
      
      function QueueUserWorkItem
      (
         callBack : NetFrameworkBase.System.Threading.WaitCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function QueueUserWorkItem
      (
         callBack : NetFrameworkBase.System.Threading.WaitCallback.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function UnsafeQueueUserWorkItem
      (
         callBack : NetFrameworkBase.System.Threading.WaitCallback.Kind_Ptr; 
         state : NetFrameworkBase.System.Object.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function UnsafeQueueNativeOverlapped
      (
         overlapped : NetFrameworkBase.System.Threading.NativeOverlapped.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function BindHandle
      (
         osHandle : NetFrameworkBase.IntPtr
      )
      return NetFrameworkBase.Boolean;
      
      function BindHandle
      (
         osHandle : NetFrameworkBase.System.Runtime.InteropServices.SafeHandle.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
end;
