--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2019 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-NetFramework                                                        --
--    Version   : 1.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with NetFrameworkBase.System.Object;
limited with NetFrameworkBase.System.Threading.CancellationToken;
limited with NetFrameworkBase.System.TimeSpan;
limited with NetFrameworkBase.System.Threading.WaitHandle;
limited with NetFrameworkBase.System.Threading.Tasks.Task_x;
--------------------------------------------------------------------------------
package NetFrameworkBase.System.Threading.SemaphoreSlim is
   
   type Kind is new NetFrameworkBase.System.Object.Kind with null record;
   type Kind_Ptr is access all Kind;
   type Kind_Array is array(Natural range<>) of Kind_Ptr;
   type Kind_Array_Ptr is access all Kind_Array;
   
      function CurrentCount
      (
         this : in out SemaphoreSlim.Kind
      )
      return NetFrameworkBase.Int32;
      
      function AvailableWaitHandle
      (
         this : in out SemaphoreSlim.Kind
      )
      return NetFrameworkBase.System.Threading.WaitHandle.Kind_Ptr;
      
      procedure Wait
      (
         this : in out SemaphoreSlim.Kind
      );
      
      procedure Wait
      (
         this : in out SemaphoreSlim.Kind;
         cancellationToken : NetFrameworkBase.System.Threading.CancellationToken.Kind_Ptr
      );
      
      function Wait
      (
         this : in out SemaphoreSlim.Kind;
         timeout : NetFrameworkBase.System.TimeSpan.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function Wait
      (
         this : in out SemaphoreSlim.Kind;
         timeout : NetFrameworkBase.System.TimeSpan.Kind_Ptr; 
         cancellationToken : NetFrameworkBase.System.Threading.CancellationToken.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function Wait
      (
         this : in out SemaphoreSlim.Kind;
         millisecondsTimeout : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Boolean;
      
      function Wait
      (
         this : in out SemaphoreSlim.Kind;
         millisecondsTimeout : NetFrameworkBase.Int32; 
         cancellationToken : NetFrameworkBase.System.Threading.CancellationToken.Kind_Ptr
      )
      return NetFrameworkBase.Boolean;
      
      function WaitAsync
      (
         this : in out SemaphoreSlim.Kind
      )
      return NetFrameworkBase.System.Threading.Tasks.Task_x.Kind_Ptr;
      
      function WaitAsync
      (
         this : in out SemaphoreSlim.Kind;
         cancellationToken : NetFrameworkBase.System.Threading.CancellationToken.Kind_Ptr
      )
      return NetFrameworkBase.System.Threading.Tasks.Task_x.Kind_Ptr;
      
      function Release
      (
         this : in out SemaphoreSlim.Kind
      )
      return NetFrameworkBase.Int32;
      
      function Release
      (
         this : in out SemaphoreSlim.Kind;
         releaseCount : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.Int32;
      
      procedure Dispose
      (
         this : in out SemaphoreSlim.Kind
      );
      
      function Constructor
      (
         initialCount : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.System.Threading.SemaphoreSlim.Kind_Ptr;
      
      function Constructor
      (
         initialCount : NetFrameworkBase.Int32;
         maxCount : NetFrameworkBase.Int32
      )
      return NetFrameworkBase.System.Threading.SemaphoreSlim.Kind_Ptr;
      
end;
